name: CI - Build & Push & Bump Helm tag

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allow committing the values.yaml bump
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute image tag
        id: vars
        run: echo "TAG=gh-${GITHUB_RUN_NUMBER}" >> "$GITHUB_OUTPUT"

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: ./app
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/nginx-n01717513:${{ steps.vars.outputs.TAG }}

      - name: Bump Helm values.yaml image tag
        run: |
          sed -i "s/^  tag: .*/  tag: \"${{ steps.vars.outputs.TAG }}\"/" helm/nginx-n01717513/values.yaml
          git config user.email "actions@github.com"
          git config user.name "github-actions"
          git add helm/nginx-n01717513/values.yaml
          git commit -m "ci: bump image tag to ${{ steps.vars.outputs.TAG }}" || echo "no changes"
          git push
